### ISSUE TITLE
白名单模式如何配置

### ISSUE THREAD

**Issue by bymao** [JasonKhew96/biliroaming-go-server#13]
想弄个几个朋友用用的自建。
服务器已搭好。就是配置配置白名单的时候一直没生效。

我自建了个黑白名单API，类似下面
`https://xxx.xyz/uuu.php?uid=%d`

白名单用户返回如下：
`{"code":0,"message":"","data":{"uid":000000,"is_blacklist":false,"is_whitelist":true,"status":0,"ban_until":0}}`

其他用户返回如下：
`{"code":0,"message":"","data":{"uid":111111,"is_blacklist":true,"is_whitelist":false,"status":1,"ban_until":3378165257}}`

config.yml配置如下：
```
# 黑名单接口
blacklistApiUrl: https://xxx.xyz/uuu.php?uid=%d
# 黑白名单模式
# 0 - 禁用
# 1 - 黑白名单
# 2 - 白名单
blockType: 1
```

blockType 我试过1和2好像都不行。
blockType 配置成2的时候。返回的status为2。但是失败了。

**Comment by JasonKhew96** [comment]
白名单 `status` 2 呀，`is_blacklist` `is_whitelist` 已经弃用了的，放着向后兼容而已
![image](https://user-images.githubusercontent.com/29531167/231680736-53e1f8a6-ae94-43c8-8073-c96ad40d6bcb.png)
